const mockMentors = [
  {
    id: 1,
    name: 'Aisha Patel',
    title: 'Senior Software Engineer',
    company: 'Stripe',
    industry: 'tech',
    bio: 'Full-stack engineer with a love for distributed systems and developer tooling. I help early-career engineers navigate Big Tech interviews and grow into strong generalists.',
    years_experience: 9,
    expertise: ['System Design', 'JavaScript', 'Career Growth', 'Interview Prep'],
    rating: 4.9,
    total_sessions: 87,
  },
  {
    id: 2,
    name: 'Marcus Webb',
    title: 'Investment Analyst',
    company: 'Blackstone',
    industry: 'finance',
    bio: 'I work on private equity deals and love helping people break into finance — whether from a non-target school or a different industry entirely.',
    years_experience: 7,
    expertise: ['Private Equity', 'Financial Modeling', 'Networking', 'Resume Review'],
    rating: 4.7,
    total_sessions: 54,
  },
  {
    id: 3,
    name: 'Dr. Lena Kim',
    title: 'Clinical Data Scientist',
    company: 'Mayo Clinic',
    industry: 'healthcare',
    bio: 'Bridging medicine and machine learning. I mentor people transitioning from clinical roles into health-tech and data science positions.',
    years_experience: 11,
    expertise: ['Health Data', 'Python', 'Clinical Research', 'Career Transitions'],
    rating: 4.8,
    total_sessions: 63,
  },
  {
    id: 4,
    name: 'Jordan Rivers',
    title: 'Head of Growth',
    company: 'Notion',
    industry: 'marketing',
    bio: 'Growth marketer who has scaled B2B SaaS from 0 to 7 figures. I focus on go-to-market strategy, content-led growth, and building the right metrics from day one.',
    years_experience: 8,
    expertise: ['GTM Strategy', 'Content Marketing', 'Analytics', 'B2B SaaS'],
    rating: 4.6,
    total_sessions: 41,
  },
  {
    id: 5,
    name: 'Tariq Hassan',
    title: 'ML Engineer',
    company: 'DeepMind',
    industry: 'data science',
    bio: 'I work on reinforcement learning research and love mentoring people getting into ML — from complete beginners to PhD students entering industry.',
    years_experience: 6,
    expertise: ['Machine Learning', 'Python', 'Research', 'Deep Learning'],
    rating: 4.9,
    total_sessions: 72,
  },
  {
    id: 6,
    name: 'Sofia Reyes',
    title: 'Product Manager',
    company: 'Figma',
    industry: 'tech',
    bio: 'I went from UX design to PM and have helped dozens of designers, engineers, and MBAs make the same move. Let\'s talk roadmaps, prioritisation, and stakeholder alignment.',
    years_experience: 5,
    expertise: ['Product Strategy', 'UX', 'Roadmapping', 'Career Pivots'],
    rating: 4.7,
    total_sessions: 39,
  },
  {
    id: 7,
    name: 'Daniel Osei',
    title: 'Venture Capital Associate',
    company: 'Sequoia Capital',
    industry: 'finance',
    bio: 'Former founder turned VC. I help founders sharpen their pitch, understand term sheets, and navigate early fundraising — especially first-time founders from underrepresented backgrounds.',
    years_experience: 10,
    expertise: ['Venture Capital', 'Fundraising', 'Pitch Decks', 'Startup Strategy'],
    rating: 4.8,
    total_sessions: 58,
  },
  {
    id: 8,
    name: 'Priya Nair',
    title: 'Biotech Consultant',
    company: 'McKinsey & Company',
    industry: 'healthcare',
    bio: 'Healthcare strategy consultant with an MD background. I mentor people interested in med-tech, life sciences consulting, and the business side of healthcare.',
    years_experience: 12,
    expertise: ['Healthcare Strategy', 'Life Sciences', 'Consulting', 'Med-Tech'],
    rating: 4.6,
    total_sessions: 47,
  },
  {
    id: 9,
    name: 'Ethan Zhao',
    title: 'Data Engineering Lead',
    company: 'Snowflake',
    industry: 'data science',
    bio: 'I build data platforms at scale. I mentor data engineers and analysts who want to up-skill in modern data stack tools, cloud infrastructure, and pipeline design.',
    years_experience: 8,
    expertise: ['Data Engineering', 'SQL', 'Cloud', 'dbt', 'Spark'],
    rating: 4.7,
    total_sessions: 66,
  },
  {
    id: 10,
    name: 'Camille Fontaine',
    title: 'Brand Strategist',
    company: 'LVMH',
    industry: 'marketing',
    bio: 'Luxury brand strategist who has worked across Europe and North America. I help creatives and marketers build a personal brand and break into premium consumer industries.',
    years_experience: 14,
    expertise: ['Brand Strategy', 'Luxury Marketing', 'Storytelling', 'Personal Branding'],
    rating: 4.5,
    total_sessions: 33,
  },
  {
    id: 11,
    name: 'Ryan Nakamura',
    title: 'DevOps Engineer',
    company: 'Cloudflare',
    industry: 'tech',
    bio: 'I live in the infrastructure layer — Kubernetes, CI/CD, observability. I mentor engineers who want to move into platform or SRE roles and get serious about reliability.',
    years_experience: 7,
    expertise: ['Kubernetes', 'CI/CD', 'AWS', 'SRE', 'Observability'],
    rating: 4.8,
    total_sessions: 45,
  },
  {
    id: 12,
    name: 'Amara Diallo',
    title: 'UX Research Lead',
    company: 'Spotify',
    industry: 'tech',
    bio: 'Mixed-methods researcher passionate about inclusive design. I help designers and researchers find their voice in product teams and advocate for the user in every room.',
    years_experience: 9,
    expertise: ['UX Research', 'Inclusive Design', 'Qualitative Methods', 'Portfolio Review'],
    rating: 4.9,
    total_sessions: 79,
  },
];

export default mockMentors;
